package com.atelierapps.vault.ui.home

import androidx.compose.foundation.horizontalScroll
import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.verticalScroll
import androidx.compose.material3.AlertDialog
import androidx.compose.material3.AssistChip
import androidx.compose.material3.FilterChip
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.OutlinedTextField
import androidx.compose.material3.Text
import androidx.compose.material3.TextButton
import androidx.compose.runtime.Composable
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateListOf
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.setValue
import androidx.compose.ui.Modifier
import androidx.compose.ui.text.input.TextFieldValue
import androidx.compose.ui.unit.dp
import com.atelierapps.vault.data.entity.MediaWithTags
import com.atelierapps.vault.data.entity.TagEntity
import com.atelierapps.vault.media.NameTemplate
import com.atelierapps.vault.ui.theme.Brass
import com.atelierapps.vault.ui.theme.Danger
import com.atelierapps.vault.ui.theme.Ink
import com.atelierapps.vault.ui.theme.Muted
import com.atelierapps.vault.ui.theme.SectionLabel

/**
 * Name, tag and file a selection in one pass.
 *
 * Three things a freshly-imported batch needs, behind one button, because doing
 * them separately means finding the same forty items three times over.
 *
 * The template is built by tapping tokens rather than typing braces — nobody
 * should have to learn a syntax to rename forty files — and the preview under
 * the field is generated by the same code that does the rename, so what it
 * shows is what you get.
 */
@Composable
fun OrganiseDialog(
    selection: List<MediaWithTags>,
    existingTags: List<TagEntity>,
    onApply: (template: String, dateFormat: String, tags: List<String>, source: String?) -> Unit,
    onDismiss: () -> Unit,
) {
    var template by remember { mutableStateOf(TextFieldValue("")) }
    var dateFormat by remember { mutableStateOf(NameTemplate.DATE_FORMATS.first()) }
    val pickedTags = remember { mutableStateListOf<String>() }
    var newTags by remember { mutableStateOf("") }
    var source by remember { mutableStateOf("") }

    fun insert(marker: String) {
        val text = template.text
        val at = template.selection.end.coerceIn(0, text.length)
        val next = text.substring(0, at) + marker + text.substring(at)
        template = TextFieldValue(next, androidx.compose.ui.text.TextRange(at + marker.length))
    }

    val renaming = template.text.isNotBlank()

    AlertDialog(
        onDismissRequest = onDismiss,
        title = { Text("Organise ${selection.size} item(s)") },
        text = {
            Column(Modifier.verticalScroll(rememberScrollState())) {
                SectionLabel("Name")
                Text(
                    "Tap a piece to add it. Everything else you type is kept as-is, " +
                        "and the extension is never touched.",
                    color = Muted,
                    style = MaterialTheme.typography.bodySmall,
                    modifier = Modifier.padding(top = 4.dp, bottom = 8.dp),
                )
                Row(
                    horizontalArrangement = Arrangement.spacedBy(6.dp),
                    modifier = Modifier.fillMaxWidth().horizontalScroll(rememberScrollState()),
                ) {
                    NameTemplate.Token.entries.forEach { token ->
                        AssistChip(
                            onClick = { insert(token.marker) },
                            label = { Text(token.label) },
                        )
                    }
                }
                OutlinedTextField(
                    value = template,
                    onValueChange = { template = it },
                    placeholder = { Text("Leave empty to keep current names") },
                    singleLine = true,
                    modifier = Modifier.fillMaxWidth().padding(top = 8.dp),
                )

                if (renaming && template.text.contains(NameTemplate.Token.DATE.marker)) {
                    Text(
                        "Date format",
                        color = Ink,
                        style = MaterialTheme.typography.bodySmall,
                        modifier = Modifier.padding(top = 10.dp, bottom = 4.dp),
                    )
                    Row(
                        horizontalArrangement = Arrangement.spacedBy(6.dp),
                        modifier = Modifier.fillMaxWidth().horizontalScroll(rememberScrollState()),
                    ) {
                        NameTemplate.DATE_FORMATS.forEach { format ->
                            FilterChip(
                                selected = format == dateFormat,
                                onClick = { dateFormat = format },
                                label = { Text(format) },
                            )
                        }
                    }
                }

                if (renaming) {
                    // Generated by the same function that performs the rename,
                    // so the preview cannot promise something else.
                    Text(
                        "Preview",
                        color = Ink,
                        style = MaterialTheme.typography.bodySmall,
                        modifier = Modifier.padding(top = 12.dp, bottom = 4.dp),
                    )
                    selection.take(3).forEachIndexed { index, item ->
                        Text(
                            NameTemplate.expand(
                                template.text, item, index, selection.size, dateFormat,
                            ),
                            color = Brass,
                            style = MaterialTheme.typography.bodySmall,
                        )
                    }
                    if (selection.size > 3) {
                        Text(
                            "…and ${selection.size - 3} more",
                            color = Muted,
                            style = MaterialTheme.typography.bodySmall,
                        )
                    }
                    if (NameTemplate.isAmbiguous(template.text)) {
                        Text(
                            "Every item would get the same name. Add Number or Original " +
                                "so they stay tellable apart.",
                            color = Danger,
                            style = MaterialTheme.typography.bodySmall,
                            modifier = Modifier.padding(top = 6.dp),
                        )
                    }
                }

                SectionLabel("Tags", Modifier.padding(top = 18.dp))
                if (existingTags.isNotEmpty()) {
                    Row(
                        horizontalArrangement = Arrangement.spacedBy(6.dp),
                        modifier = Modifier.fillMaxWidth()
                            .horizontalScroll(rememberScrollState())
                            .padding(top = 6.dp),
                    ) {
                        existingTags.forEach { tag ->
                            val on = pickedTags.any { it.equals(tag.name, ignoreCase = true) }
                            FilterChip(
                                selected = on,
                                onClick = {
                                    if (on) pickedTags.removeAll { it.equals(tag.name, ignoreCase = true) }
                                    else pickedTags.add(tag.name)
                                },
                                label = { Text("#" + tag.name) },
                            )
                        }
                    }
                }
                OutlinedTextField(
                    value = newTags,
                    onValueChange = { newTags = it },
                    placeholder = { Text("New tag(s), comma-separated") },
                    singleLine = true,
                    modifier = Modifier.fillMaxWidth().padding(top = 8.dp),
                )

                SectionLabel("Source", Modifier.padding(top = 18.dp))
                OutlinedTextField(
                    value = source,
                    onValueChange = { source = it },
                    placeholder = { Text("Leave empty to keep what's recorded") },
                    singleLine = true,
                    modifier = Modifier.fillMaxWidth().padding(top = 6.dp),
                )
            }
        },
        confirmButton = {
            val ambiguous = renaming && NameTemplate.isAmbiguous(template.text)
            TextButton(
                enabled = !ambiguous,
                onClick = {
                    val tags = (pickedTags + newTags.split(","))
                        .map { it.trim() }
                        .filter { it.isNotEmpty() }
                        .distinctBy { it.lowercase() }
                    onApply(template.text, dateFormat, tags, source.ifBlank { null })
                },
            ) { Text("Apply", color = if (ambiguous) Muted else Brass) }
        },
        dismissButton = { TextButton(onClick = onDismiss) { Text("Cancel") } },
    )
}
